### ISSUE TITLE
Install via Homebrew!

### ISSUE THREAD

**Issue by c5f** [walle/wiki#10]
Would like to `brew install wiki` this tool.

**Comment by walle** [comment]
Good idea! I will look into packaging the tool for homebrew.

**Comment by walle** [comment]
I have added a pull request to Homebrew with the formula, we will see if it gets accepted.

https://github.com/Homebrew/homebrew/pull/44844

**Comment by c5f** [comment]
thanks duder.

**Comment by walle** [comment]
The pull request is merged now, I guess you saw that. Thanks for the push
to submit it to homebrew.
