### ISSUE TITLE
[Feature request] Control width, paragraph breaks?

### ISSUE THREAD

**Issue by dieggsy** [walle/wiki#13]
Not sure how feasible this is but it would be nice to be able to control the wrap width of the text (say wrap it to 80 chars if I wanted) and have blank line breaks between paragraphs.

**Comment by dieggsy** [comment]
Actually, the wrap can be controlled with `wiki example | fold -w 80 -s`, but I've yet to find a solution for blank line between paragraphs.

**Comment by dieggsy** [comment]
For reference, based on [this](https://stackoverflow.com/questions/1251999/how-can-i-replace-a-newline-n-using-sed#1252010), you can use:

GNU sed:
` wiki example | sed ':a;N;$!ba;s/\n/\n\n/g' | fold -w 80 -s`

Cross-platform:
`wiki example | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g' | old -w 80 -s`

Would still be nice to get the option built in, but I can use this workaround if needed

**Comment by walle** [comment]
Great idea!

I've updated the tool to version 1.4.0 which has this functionality.

Paragraphs are done by default and there is a flag `-w` for setting the wrapping width.

Thank you for your contribution!
