### ISSUE TITLE
Feature Request: Ignore SSL

### ISSUE THREAD

**Issue by Stolas** [walle/wiki#3]
I have an invalid SSL Certificate, I would like a --no-cert kind of filter.

**Comment by walle** [comment]
I'm working on a patch to add this feature.

**Comment by walle** [comment]
I have added a new flag `-no-check-certificate` 

Does this work for you?

**Comment by Stolas** [comment]
@walle yes, perfect. Thank you.

**Comment by walle** [comment]
No problem. I hope it will be useful!
