### ISSUE TITLE
Forced strings.Title on page titles breaks some pages

### ISSUE THREAD

**Issue by ojii** [walle/wiki#4]
I ran:

```
$ wiki SASL
SASL may refer to:
Simple Authentication and Security Layer, a framework for authentication and data security in Internet protocols
SASL (programming language), a non-strict functional programming language developed by David Turner in 1976
South African Sign Language, an officially-recognized sign language in South Africa
Solitaire Advanced Squad Leader, a single-player variant of the World War II board wargame Advanced Squad Leader
System Application Support Libraries, an application of the Erlang programming language
South African Soccer League, a former association football league based in South Africa

Read more: https://en.wikipedia.org/wiki/SASL
$ wiki Simple Authentication and Security Layer
No such page
Create it on: https://en.wikipedia.org/wiki/Simple_Authentication_And_Security_Layer
```

The correct URL for the page is `https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer` (lowercase `and`).

**Comment by walle** [comment]
Aha, this is because I use strings.Title (https://golang.org/pkg/strings/#Title) on the query. I added it because I'm lazy and don't want to do that manually. But it seems like it may cause more problems, my guess is that there are a couple of pages with and, of and so on in the title.

I will look into this.

**Comment by walle** [comment]
I have removed the strings.Title.

Now you can call `$ wiki Simple Authentication and Security Layer`

You can also call `$ wiki tom petty`  and the mediawiki API redirects you to the correct page.
